name = "Course_order_suggestion_system"
description = "NTUST course order suggestion system"
version = "0.0.1"
terminal = false
packages = [
    "/testweb/static/wheels/aiohttp-3.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "/testweb/static/wheels/aiosignal-1.3.1-py3-none-any.whl",
    "/testweb/static/wheels/async_timeout-4.0.3-py3-none-any.whl",
    "/testweb/static/wheels/attrs-23.2.0-py3-none-any.whl",
    "/testweb/static/wheels/course_order_suggestion_system-0.0.1-py3-none-any.whl",
    "/testweb/static/wheels/frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "/testweb/static/wheels/idna-3.7-py3-none-any.whl",
    "/testweb/static/wheels/multidict-6.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "/testweb/static/wheels/toga_core-0.4.2-py3-none-any.whl",
    "/testweb/static/wheels/toga_web-0.4.2-py3-none-any.whl",
    "/testweb/static/wheels/travertino-0.3.0-py3-none-any.whl",
    "/testweb/static/wheels/yarl-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
]

[splashscreen]
autoclose = true
