name = "Course_order_suggestion_system"
description = "NTUST course order suggestion system"
version = "0.0.1"
terminal = false
packages = [
    "ssl",
    "/testweb/static/wheels/course_order_suggestion_system-0.0.1-py3-none-any.whl",
    "/testweb/static/wheels/toga_core-0.4.2-py3-none-any.whl",
    "/testweb/static/wheels/toga_web-0.4.2-py3-none-any.whl",
    "/testweb/static/wheels/travertino-0.3.0-py3-none-any.whl",
]

[splashscreen]
autoclose = true
